test_add (__main__.TestCase)
这里最好加上注释, 便于后续定位用例 ... ok
test_minus (__main__.TestCase)
由于成功失败是以用例为单位的, 不建议一个用例里面加太多assert ... FAIL
test_add (__main__.TestCase)
这里最好加上注释, 便于后续定位用例 ... ok

======================================================================
FAIL: test_minus (__main__.TestCase)
由于成功失败是以用例为单位的, 不建议一个用例里面加太多assert
----------------------------------------------------------------------
Traceback (most recent call last):
  File "solution-4.py", line 46, in test_minus
    self.assertEqual(1, minus(3, 1))
AssertionError: 1 != 2

----------------------------------------------------------------------
Ran 3 tests in 0.001s

FAILED (failures=1)
